/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AInput: typeof import('ant-design-vue/es')['Input']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    Contents: typeof import('./components/layouts/contents.vue')['default']
    Flip: typeof import('./components/flips/flip.vue')['default']
    Flows: typeof import('./components/workflows/flows.vue')['default']
    FlowsConfigs: typeof import('./components/workflows/flows-configs.vue')['default']
    FlowsNode: typeof import('./components/workflows/flows-node.vue')['default']
    Group: typeof import('./components/flips/group.vue')['default']
    Layout: typeof import('./components/layouts/layout.vue')['default']
    LayoutPlatform: typeof import('./components/layouts/layout-platform.vue')['default']
    MenuItem: typeof import('./components/layouts/menu-item.vue')['default']
    Roller: typeof import('./components/flips/roller.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Using: typeof import('./components/chats/using.vue')['default']
    View: typeof import('./components/chats/view.vue')['default']
  }
}
